### ISSUE TITLE
"Erstellen" button links to a 404 Page

### ISSUE THREAD

**Issue by QuantumNeutron** [Libre-TrainSim/Libre-TrainSim#518] opened 2023-06-21 21:24 UTC
https://www.libre-trainsim.de/contribute is 404. I can't access the page

**Comment by QuantumNeutron** [comment] 2023-06-21 21:25
OS: Arch Linux 64, current version
Game version 0.8

**Comment by HaSa1002** [comment] 2023-06-25 20:54
duplicate of #292
The domain changed to https://www.libretrainsim.org/contribute/ and we can't push a hotfix for 0.8. As 0.9 should be ready as soon as the maps are finalised (which quite frankely is an objective for a couple of months now), the situation should resolve itself soonish

**Closed as completed by HaSa1002** 2023-06-25 20:54 UTC
Labels: archive
