### ISSUE TITLE
About the app falling on the way

### ISSUE THREAD

**Issue by iskdjfjdjakdkfkksjhjdjs** [Libre-TrainSim/Libre-TrainSim#448] opened 2022-12-24 05:21 UTC
When you try to start the game, the app falls on the way. This won't play. What should I do?

**Comment by nalquas** [comment] 2022-12-24 12:43
Hi, thanks for leaving an issue report. Could you please give more detail about what went wrong so we can investigate?

More specifically, please provide:

- summary
- how to reproduce
- observed behavior
- expected behavior
- your game version and operating system

Thanks.

**Comment by nalquas** [comment] 2023-01-01 20:48
Closing due to lack of information.

**Closed as not planned by nalquas** 2023-01-01 20:48 UTC
Labels: archive
