### ISSUE TITLE
mac control keys are not supported

### ISSUE THREAD

**Issue by dictonary** [Libre-TrainSim/Libre-TrainSim#261] opened 2021-11-18 03:27 UTC
keys to control things like f1 f2 and f3 all have purposes on mac so if you click them for example f1 does brightness down f2 does brightens up and f3 opens something called control center witch shows all open windows on the computer so i cant do the functions they can do in the game

**Comment by HaSa1002** [comment] 2021-11-18 11:22
Are you sure, you don't have a FN key? You usally can toggle between function states with that key.

Related to #35

**Comment by dictonary** [comment] 2022-01-24 02:20
i did not know i could use fn key thank you for telling me that HaSa1002

**Comment by nalquas** [comment] 2022-08-20 14:24
> i did not know i could use fn key thank you for telling me that HaSa1002

I'll go ahead and close the issue as it works as intended, then.

**Closed as completed by nalquas** 2022-08-20 14:24 UTC
Labels: archive, macos
